version: "3"

services:

  db:
    image: mysql:latest
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    expose:
      - "3306"
    ports:
      - "3307:3306"
    volumes:
      - "../NearbyAssist/internal/db/migrations/20231231015242_init.up.sql:/docker-entrypoint-initdb.d/init.sql"
      - "./mysql:/var/lib/mysql"
    networks:
        - nearbyassist

  osrm:
    image: ghcr.io/project-osrm/osrm-backend
    container_name: osrm
    command: osrm-routed --algorithm mld /data/philippines-latest.osrm
    expose:
      - "5000"
    volumes:
      - "../osrm-backend/:/data"
    networks:
        - nearbyassist

  backend:
    build:
      context: ../NearbyAssist/
      dockerfile: ./Dockerfile
    container_name: backend
    restart: on-failure
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_started
      osrm: 
        condition: service_started
    environment:
      DB_HOST: db
    env_file:
      - ../NearbyAssist/.env
    networks:
        - nearbyassist

  web:
    build:
      context: ../NearbyAssist_web/
      dockerfile: ./Dockerfile
    container_name: web
    restart: on-failure
    ports:
      - "3001:80"
    depends_on:
      - backend 
    env_file:
      - ../NearbyAssist_web/.env
    networks:
        - nearbyassist

  proxy:
    image: nginx:alpine
    container_name: proxy
    restart: on-failure
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web 
      - backend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./logs:/var/log/nginx/
    networks:
      - nearbyassist

networks:
  nearbyassist:

volumes:
  logs:
